version: '3'
services:
  tomcat:
    build: ./tomcat
    image: <account_id>.dkr.ecr.ap-northeast-1.amazonaws.com/tomcat10
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "8080:8080"
  web:
    build: ./nginx
    image: <account_id>.dkr.ecr.ap-northeast-1.amazonaws.com/nginx1192
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
